name:                wfc-hs
version:             0.1.0.0
github:              "cocreature/wfc-hs"
license:             BSD3
author:              "Moritz Kiefer"
maintainer:          "moritz.kiefer@purelyfunctional.org"
copyright:           "(C) 2018 Moritz Kiefer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cocreature/wfc-hs#readme>

dependencies:
- base >= 4.10 && < 4.11
- containers >= 0.5 && < 0.6
- massiv >= 0.1 && < 0.2
- massiv-io >= 0.1 && < 0.2
- MonadRandom >= 0.5 && < 0.6
- mtl >= 2.2 && < 2.3
- protolude >= 0.2 && < 0.3
- random >= 1.1 && < 1.2

default-extensions:
- BangPatterns
- DeriveFunctor
- DeriveFoldable
- FlexibleContexts
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- TupleSections
ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  wfc-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit >= 1.3 && < 1.4
    - resourcet >= 1.2 && < 1.3
    - wfc-hs
    - xml-conduit >= 1.8 && < 1.9
    - xml-types >= 0.3 && < 0.4

tests:
  wfc-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wfc-hs
