resolver: lts-10.5
packages:
- .
extra-deps:
- git: git@github.com:lehins/massiv.git
  commit: 34bfc0023c2c636d1af06e58f80b953cd888ef8e
  subdirs:
    - massiv
    - massiv-io
- conduit-1.3.0
- conduit-extra-1.3.0
- xml-conduit-1.8.0
- resourcet-1.2.0
